### ISSUE TITLE
Question about import of Three.js

### ISSUE THREAD

**Issue by git-headswap** [svierk/awesome-lwc-collection#92]
After multiple hours, I cant get the three js to be imported correctly. Please help.

Full question: https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007epl2WSAQ

**Comment by svierk** [comment]
Hi @git-headswap, 
unfortunately, the linked question is not currently accessible to me. It would be great if you could either explain it here with few more details or instead make it accessible please.

<img width="1372" alt="image" src="https://github.com/svierk/awesome-lwc-collection/assets/16227041/9f08baf8-2d17-4c1f-a81d-02bb4809f484">

**Comment by svierk** [comment]
@git-headswap since there has been no further response to this in the last few days, I will close the thread.

However, here are a few notes on using the component:

1. A working version of the three.js library is already included and prepared in this repository as a static resource, which is referenced by the LWC. If this has been correctly deployed to your org, everything should work.
2. Please also check whether Lightning Web Security is enabled in your org, otherwise this can also be a possible source of errors.
